---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Ubuntu 16.04 Nginx web server based on https://github.com/drpventura/cloud-formation/blob/master/mapping-ubuntu-web.yaml, last access 2/24/2018

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: 'The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    
Mappings:
  Region2AMI:
    us-east-1:
      AMI: ami-cd0f5cb6
    us-east-2:
      AMI: ami-10547475
    us-west-1:
      AMI: ami-07585467
    us-west-2:
      AMI: ami-79873901
    ap-south-1:
      AMI: ami-84e3b2eb
    ap-northeast-2:
      AMI: ami-ab77d4c5
    ap-southeast-1:
      AMI: ami-b7f388cb
    ap-southeast-2:
      AMI: ami-942dd1f6
    ap-northeast-1:
      AMI: ami-48630c2e
    ca-central-1:
      AMI: ami-173db873
    eu-central-1:
      AMI: ami-5055cd3f
    eu-west-1:
      AMI: ami-1b791862
    eu-west-2:
      AMI: ami-941e04f0
    eu-west-3:
      AMI: ami-c1cf79bc
    sa-east-1:
      AMI: ami-bb9bd7d7
      
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: t2.micro
      SecurityGroups: 
      - !Ref WebserverSecurityGroup
      Tags:
      - Key: Name
        Value: Ubuntu16 Web + SSH Server 
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': |
          #!/bin/bash
          set -e
          set -x
          # Set timezone
          sudo timedatectl set-timezone America/New_York
          
          # fix color of directory, which in PuTTy ends up as dark blue on 
          # black background
          bashrc_append=$(cat <<'EOT'
          d=.dircolors
          test -r $d && eval "$(dircolors $d)"
          EOT
          )
          echo "$bashrc_append" >> /home/ubuntu/.bashrc
          dircolors -p > /home/ubuntu/.dircolors
          sed -i -e 's/DIR 01;.*/DIR 01;36 # directory/' /home/ubuntu/.dircolors
          sudo chown ubuntu:ubuntu /home/ubuntu/.dircolors
          sudo apt-get update
          sudo apt-get install -y nginx
          cd /var/www/html
          echo "<html><head><title>Phil Sellick</title></head><body><h1>Phil Sellick</h1></body></html>" >index.html
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: hello-world-webserver
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation
Outputs:
  Region:
    Description: The Region we are in.
    Value: !Ref 'AWS::Region'